NA: 1
color:
- 255
- 255
- 255
color_picked:
- 255
- 255
- 255
color_picker_counter: 0
default:
- - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
- - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
- - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
- - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
- - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 255
    - 255
    - 255
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
- - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
- - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
- - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
exposure_time_BF: 73
exposure_time_FLUO: 11
intensity: 43
intensity_expt: 86
matrixdim:
- 8
- 8
picked:
- 255
- 255
- 255
update_fluoled_active: false
update_matrix_active: false
user:
- - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
- - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
- - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
- - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - &id001
    - 255
    - 255
    - 255
  - *id001
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
- - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 255
    - 255
    - 255
  - *id001
  - *id001
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
- - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
- - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
- - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
  - - 0
    - 0
    - 0
